version: '3.8'
services:
  db:
    restart: always
    image: "postgres:14.3-alpine"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=clients_db
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

volumes:
  db_data:
    driver: local
